### ISSUE TITLE
vue 版本现在发到 3.x 了，引入时需要指定 vue2 版本，否则会出错

### ISSUE THREAD

**Issue by illuz** [Monibuca/webrtc-publish#1]
https://github.com/Monibuca/webrtc-publish/blob/f424f6af72a1773d6f83958d2b9fcd171d7b2e7e/index.html#L32

打开项目引用的链接后会跳转到 vue3：
https://unpkg.com/vue/dist/vue.js -> https://unpkg.com/vue@3.2.36/dist/vue.js

建议改成指定 vue2 版本：
https://unpkg.com/vue@2/dist/vue.js

**Comment by bosscheng** [comment]
@illuz 好的，谢谢
